# Generated by Django 4.1.13 on 2026-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='completed',
            field=models.CharField(choices=[('not_started', 'Not Yet Started'), ('started', 'Started'), ('progress', 'Progress'), ('pending', 'Pending'), ('Completed', 'Completed')], default='not_started', max_length=30),
        ),
    ]
